Create portfolio headline
wacoo/Portfolio-Project-Attempt-1 pull request #1
Opened 2023-06-01 16:36 UTC by wacoo

- Add index.html file
- Create static folder
- Create images folder
- Add images to images folder
- Create gitignore file
- Add github linter configuration
- Design protfolio page for mobile devices

2023-06-01 17:36 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @wacoo 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 17:36 UTC, tresorsawasawa commented on index.html
> +      </div>
- [ ] As required for the project, kindly ensure that your logo has a link (i.e. `<a>` tag) for the following three reasons: convention, semantics, and user experience(UX).

2023-06-01 17:36 UTC, tresorsawasawa commented on index.html
> +      </section>
- [ ] For best semantics tags, I think it would be better if you replace each above `section` tag with a `div`. The `section` tag should wrap all the code from `line 26` to `line 43`

2023-06-01 17:36 UTC, tresorsawasawa commented on index.html
> +      </section>
- [ ] As required for project and for best semantics tag, kindly ensure that the container of the section is a `section` tag i.e all the selected code lines. It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.The container of the section is a section tag.

- [ ] As required for the project, kindly make sure the content og the section is aligned with flexbox. This gives us a lot of options to align all our elements, plus, it's responsive.

2023-06-01 17:36 UTC, tresorsawasawa commented on index.html
> +      </div>
- [ ] As required for the project and for semantics reasons, kindly make sure The hamburger button has a `nav` tag. The `nav` tag is for semantics reason, and the right position for convention and user experience for mobile devices.

2023-06-01 17:36 UTC, tresorsawasawa commented on index.html
> +      </section>
- [ ] Kindly make sure the list of icons uses a `ul` tag to group them and not a `section` tag, and `li` per icon; each icon has a link (`a` tag). Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using `href` attribute.

2023-06-01 17:36 UTC, tresorsawasawa commented on index.html
> +          you see and have a project you need coded, don't hesitate to contact me.</p>
- [ ] To match your chosen Figma design, kindly make sure you use the correct font-size to description paragraph as the current one is different to the one used on Figma

2023-06-02 09:39 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @wacoo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 09:39 UTC, bobb-Rob commented on index.html
> +  <section class="container">
- [ ] I think you misunderstood the previous reviewer or he was not clear enough. The  `<section class="container">` should be a `div` and not a `section` tag, because `section` tags are used to demarcate portions of the web element that are related together. Kindly change it to a `div` tag.
- [ ] The `main` element you used on your page be a `section` tag since that element within are all related - Headline.

See below the correct HTML structure: 

```html
<body>
  <div class="container">
    <header class="head">
      <div class="logo">
        <a href="#"><img src="/static/images/logo.jpg" alt="W logo"></a>
      </div>
      <nav class="menu">
        <img src="/static/images/burger.PNG" alt="Menu">
      </nav>
    </header>
    <section class="content">
      <div class="name">
        <h1> Hey There.</h1>
        <h1>I'm Wonde.</h1>
      </div>
      <div class="job">
        <h3>I'm a Software Developer</h3>
      </div>
      <div class="description">
        <p>I can help build a product, feature or website look through some of my work and experience! If you like what
          you see and have a project you need coded, don't hesitate to contact me.</p>
      </div>
      <div class="social">
        <ul>
          <li>
            <a href="https://github.com/wacoo"><img src="/static/images/github.png" alt="Github"></a>
          </li>
          <li>
            <a href="https://linkedin.com/in/wondmagegn-abriham-b867289a"><img src="/static/images/linkedin.png" alt="Linkedin"></a>
          </li>
          <li>
            <a href="#"><img src="/static/images/peace.png" alt="Angel List"></a>
          </li>

          <li>
            <a href="https://twitter.com/wabaham9"><img src="/static/images/twitter.png" alt="Twitter"></a>
          </li>
          <li>
            <a href="#"><img src="/static/images/m.png" alt="Medium"></a>
          </li>
        </ul>
      </div>
    </section>
  </div>

</body>
```

2023-06-02 09:39 UTC, bobb-Rob commented on index.html
> +        <h1>I'm Wonde.</h1>
- [ ] [OPTIONAL] Please collapse this into one `h1` tag and use `br` tag to break the `I'm Wonde` to the next line, instead of two separate `h1` tags.

_**This comment is marked as optional because the previous reviewer did not mention it, but I recommend you fix it to improve your work further.**_

2023-06-02 09:39 UTC, bobb-Rob commented on index.html
> +      </nav>
- [ ] The hamburger icon is touching the edge of the web page. This issue was not there before the first reviewer made his comments. I believe I was introduced after you added the `nav` tag. Kindly add the correct margin-right.

You work now 👇🏾 
![image](https://github.com/wacoo/Portfolio-Project/assets/84156714/f3917604-e786-43f3-b849-e223e400f109)

What it should be
![image](https://github.com/wacoo/Portfolio-Project/assets/84156714/7fedb2ba-6cdf-4799-8f84-8b65d82ce5f9)

2023-06-02 09:39 UTC, bobb-Rob commented on index.html
> +    </header>
- [ ] [OPTIONAL] The distance between the navbar and the headline text - `Hey there ....` is too large compared to the Figma design. Kindly adjust it to the correct spacing - 120px.

_**This comment is marked as optional because the previous reviewer did not mention it, but I recommend you fix it to improve your work further.**_

2023-06-02 10:45 UTC, Shedrack-Sunday approved these changes
Hi @wacoo  👋

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

![image](https://i.pinimg.com/originals/3d/d2/07/3dd207237b39dcacd832f94a35428255.gif)


## Highlights
- Good job with the design ✔️ 
- Kudus to meet the previous reviewer's suggestions  👍 

## Optional Suggestions 💡
While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.
Cheers, and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread, and don't forget to tag me so I'll receive the notification.

As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-02 10:45 UTC, Shedrack-Sunday commented on index.html
> +          you see and have a project you need coded, don't hesitate to contact me.</p>
- [Optional] Nice work. As a suggestion, kindly adjust the margin between your text and the background image as it is on the figma design. You'll agree with me that it gives a better user experience as the text in yours looks clustered in the sense of being invisible at the edges 👍 

## Your design:
![image](https://github.com/wacoo/Portfolio-Project/assets/50990925/1bb9f0e0-ab11-4ef9-b799-d879e39bf8c7)

## Figma:
![image](https://github.com/wacoo/Portfolio-Project/assets/50990925/7f8f50b9-fb76-4530-a3c2-9d98b1afd68a)

2023-06-02 10:59 UTC, wacoo commented on index.html
> +          you see and have a project you need coded, don't hesitate to contact me.</p>
Thanks for the help. Regarding the optional comment, My browser shows me exactly as in the figma design. I tried to resize the browser tab, it is okay on my side. No no overlap. 
![image](https://github.com/wacoo/Portfolio-Project/assets/9458141/4aa56842-4ac2-42d3-b2ae-5c98b41b3254)
this is the minimum width. Any suggestions?

2023-06-02 11:00 UTC, merged

2023-06-02 11:02 UTC, Shedrack-Sunday commented on index.html
> +          you see and have a project you need coded, don't hesitate to contact me.</p>
Try it on a screen size of `375px`. If you get same, then try deploying it to see how it looks. If everything is fine, then you're good to go. You'll deploy by next week ✅

2023-06-02 11:03 UTC, wacoo commented on index.html
> +          you see and have a project you need coded, don't hesitate to contact me.</p>
Okay, thanks.